imports:
  - { resource: "@ArobasesSyliusProfessionalCustomerPlugin/Resources/config/grids.yaml" }
  - { resource: "@ArobasesSyliusProfessionalCustomerPlugin/Resources/config/files_uploader.yaml" }
  - { resource: "@ArobasesSyliusProfessionalCustomerPlugin/Resources/config/forms.yaml" }

sylius_mailer:
  emails:
    customer_pro_confirmation:
      subject: "Welcome !"
      template: "@ArobasesSyliusProfessionalCustomerPlugin/CustomerPro/Email/customerProConfirmation.html.twig"
    admin_customer_pro_notification:
      subject: "A new customer pro ! "
      template: "@ArobasesSyliusProfessionalCustomerPlugin/CustomerPro/Email/adminCustomerProNotification.html.twig"
    user_registration_pro:
      subject: sylius.emails.user_registration.subject
      template: "@ArobasesSyliusProfessionalCustomerPlugin/CustomerPro/Email/userRegistrationPro.html.twig"