services:
  arobases_sylius_professional_customer_plugin.promotion_rule_checker.professional_customer:
      class: Arobases\SyliusProfessionalCustomerPlugin\Promotion\Checker\Rule\ProfessionalCustomerRuleChecker
      tags:
        - { name: sylius.promotion_rule_checker, type: professional_customer, form_type: Arobases\SyliusProfessionalCustomerPlugin\Form\Type\Rule\ProfessionalCustomerConfigurationType, label: Professional Customer }

  Arobases\SyliusProfessionalCustomerPlugin\Component\Core\OrderProcessing\OrderTaxesProcessor:
    decorates: sylius.order_processing.order_taxes_processor
    arguments:
      - '@sylius.provider.channel_based_default_zone_provider'
      - '@sylius.zone_matcher'
      - '@sylius.registry.tax_calculation_strategy'
      - '@sylius.context.customer'
      - '@sylius.context.channel'

  Arobases\SyliusProfessionalCustomerPlugin\EventListener\CustomerProVerifiedListener:
    arguments:
      - '@sylius.email_sender'
      - '@sylius.context.channel'
      - '@sylius.context.locale'
    tags:
       - { name: kernel.event_listener, event: sylius.customer.post_update, method: sendUserProVerifiedEmail }

  Arobases\SyliusProfessionalCustomerPlugin\Menu\AccountMenuListener:
    arguments:
      - '@sylius.context.customer'
    tags:
      - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }