# Delete these routes and define your own shop routes here

acme_sylius_example_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Acme\SyliusExamplePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

acme_sylius_example_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Acme\SyliusExamplePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~

sylius_pro_shop_register:
    path: /pro_register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@ArobasesSyliusProfessionalCustomerPlugin/CustomerPro/pro_register.html.twig"
            form: Arobases\SyliusProfessionalCustomerPlugin\Form\Type\Customer\CustomerProRegistrationType
            event: register
            redirect:
                route: sylius_shop_account_dashboard
            flash: arobases_sylius_professional_customer:customer:register

sylius_pro_shop_account_dashboard:
    path: /pro_dashboard
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:showAction
        _sylius:
            template: "@ArobasesSyliusProfessionalCustomerPlugin/CustomerPro/Account/dashboard_pro.html.twig"
            repository:
                method: find
                arguments:
                    - "expr:service('sylius.context.customer').getCustomer()"
